package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/fatih/color"
	"github.com/frostyeti/sopsv/internal/config"
	"github.com/frostyeti/sopsv/internal/vault"
	"github.com/fsnotify/fsnotify"
	"github.com/spf13/cobra"
)

var syncCmd = &cobra.Command{
	Use:   "sync [vault_name]",
	Short: "Continuously sync a vault's decrypted secrets to a local .env file",
	Long:  "Reads the vault and writes its contents to the destination file. It then watches the vault for changes and automatically updates the destination file.",
	Args:  cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := config.GetDefaultVault()
		if len(args) > 0 {
			name = args[0]
		}

		if name == "" {
			color.Red("No vault specified and no default vault set.")
			os.Exit(1)
		}

		dest, _ := cmd.Flags().GetString("dest")

		vaultPath := vault.ResolveVaultPath(name)

		if _, err := os.Stat(vaultPath); os.IsNotExist(err) {
			color.Red("Vault %s not found", name)
			os.Exit(1)
		}

		// Initial sync
		err := performSync(name, dest)
		if err != nil {
			color.Red("Initial sync failed: %v", err)
			os.Exit(1)
		}

		color.Green("Successfully synced '%s' to '%s'", name, dest)

		watch, _ := cmd.Flags().GetBool("watch")
		if !watch {
			return
		}

		// Setup watcher
		watcher, err := fsnotify.NewWatcher()
		if err != nil {
			color.Red("Failed to create file watcher: %v", err)
			os.Exit(1)
		}
		defer watcher.Close()

		err = watcher.Add(filepath.Dir(vaultPath))
		if err != nil {
			color.Red("Failed to watch directory: %v", err)
			os.Exit(1)
		}

		color.Cyan("Watching for changes to '%s'...", vaultPath)

		// Create a debouncer to prevent rapid syncs
		var timer *time.Timer

		for {
			select {
			case event, ok := <-watcher.Events:
				if !ok {
					return
				}

				// Ensure the event was for our file (handling temporary files from sops)
				// We actually watch the directory because sops might replace the file
				if event.Name == vaultPath {
					if event.Has(fsnotify.Write) || event.Has(fsnotify.Create) {
						if timer != nil {
							timer.Stop()
						}
						timer = time.AfterFunc(100*time.Millisecond, func() {
							color.Yellow("\nDetected change, syncing...")
							if err := performSync(name, dest); err != nil {
								color.Red("Sync failed: %v", err)
							} else {
								color.Green("Sync successful at %s", time.Now().Format(time.RFC3339))
							}
						})
					}
				}
			case err, ok := <-watcher.Errors:
				if !ok {
					return
				}
				color.Red("Watcher error: %v", err)
			}
		}
	},
}

func performSync(vaultName, destFile string) error {
	data, err := vault.ReadVault(vaultName)
	if err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Generated by sopsv sync - DO NOT EDIT\n")
	for k, v := range data {
		// Escape values as needed, simple format for now
		val := fmt.Sprintf("%v", v)
		if strings.Contains(val, " ") || strings.Contains(val, "\n") || strings.Contains(val, "\"") {
			// Escape quotes
			val = strings.ReplaceAll(val, "\"", "\\\"")
			sb.WriteString(fmt.Sprintf("%s=\"%s\"\n", k, val))
		} else {
			sb.WriteString(fmt.Sprintf("%s=%s\n", k, val))
		}
	}

	return os.WriteFile(destFile, []byte(sb.String()), 0600)
}

func init() {
	rootCmd.AddCommand(syncCmd)
	syncCmd.Flags().StringP("dest", "d", ".env", "Destination file path")
	syncCmd.Flags().BoolP("watch", "w", false, "Keep running and watch for changes")
}
